local_env = Environment() # initialize the environment

library = local_env.SharedLibrary(
    target="chapter_one",
    source=["src/chapter_one.cpp"],
    CPPPATH=["src"])

main = local_env.Program(
    target="chapter_one_driver",
    source=["src/main.cpp"],
    CPPPATH=["src"],
    LIBS=[library],
    LIBPATH=["src"],
    RPATH=["src", "../build"])

# Depends(main, library)
